config/routes.rb
Rails.application.routes.draw do


  get 'regulamin', to: "static#terms", as: :terms
  get 'polityka-prywatnosci', to: "static#privacy", as: :privacy
  get 'dostawa', to: "static#shipping", as: :shipping
  get 'o-sklepie', to: "static#about", as: :about

  root to: "products#index"
  resources :products, only: [:show,:index]
  resources :categories, only: [:show]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products

	validates :name, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  validates :name, presence: true
  validates :description, presence: true
  validates :price, numericality: {greater_than: 0.0 }
  validates :category, presence: true

  mount_uploader :photo, ProductPhotoUploader  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def terms
  end

  def privacy
  end

  def shipping
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/categories/show.html.erb
<h1>Nazwa kategorii</h1>

<%= render partial: 'products/products', locals: { products: (1..9)} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<%-# Nagłówek każdej strony - POCZĄTEK -%>
  	<!-- Nagłówek każdej strony - POCZĄTEK -->
  	<nav class="navbar navbar-inverse navbar-static-top">
  		<div class="container">
  			<div class="navbar-header">
  				<a class="navbar-brand" href="<%= root_path %>">FakeShop</a>
  			</div>
  			<ul class="nav navbar-nav">
  				<li class="active"><a href="#">Start</a></li>
  				<li><a href="#">Polityka prywatności</a></li>
  				<li><a href="#">Regulamin</a></li>
  				<li><a href="#">Dostawa i płatności</a></li>
  				<li><a href="#">O sklepie</a></li>
  			</ul>
  		</div>
  	</nav>
  	<%-# Nagłówek każdej strony - KONIEC -%>
  	<!-- Nagłówek każdej strony - KONIEC -->

  	<!-- Główny kontener - POCZĄTEK -->
  	<div class="container-fluid">
  		<div class="row">
  			<!-- Side Bar Kategorie - POCZĄTEK -->
  			<div class="col-md-2">
  				<h3>Kategorie</h3>
  				<ul class="nav nav-sidebar">
  					<% (1..9).each do |category| %>
	  					<li>
	  						<%= link_to "Kategoria#{category}", category_path(category) %>
	  					</li>
	  				<% end %>
  				</ul>
  			</div>
  			<!-- Side Bar Kategorie - KONIEC -->

  			<!-- Główna treść - POCZĄTEK -->
  			<div class="col-md-10">
  				<%= yield %>
  			</div>
  			<!-- Główna treść - KONIEC -->
  		</div>
  	</div>
  	<!-- Główny kontener - KONIEC -->

    
  </body>
</html>

app/views/products/_products.html.erb
 <% products.each_slice(3) do |slice| %>
	<div class="row">
		<% slice.each do |product| %>
			<div class="col-md-4">
				<div class="thumbnail">
					<%= link_to product_path(1) do %>
						<%= image_tag Faker::Placeholdit.image("640x480", "jpg", "cccccc") %>
					<% end %>

					<div class="caption">
						<h3><%= link_to Faker::Hacker.noun.titleize, product_path(1) %></h3>
						<p><%= simple_format(truncate(Faker::Hacker.say_something_smart, length: 90)) %></p>
						<p class="lead"><%= number_to_currency Faker::Number.decimal(2,2) %></p>
						<p>
							<%= link_to "#", class: "btn btn-primary" do %>
								<span class="fa fa-shopping-cart">Dodaj do koszyka</span>
							<% end %>
						</p>
					</div>
				</div>

			</div>
		<% end %>
	</div>
<% end %>

app/views/products/index.html.erb
<h1>Najnowsze produkty w FakeShop</h1>

<%= render partial: 'products', locals: { products: (1..9)} %>

app/views/products/show.html.erb
<div class="container-fluid">
	<div class="col-md-5">
		<h1><%= Faker::Hacker.noun.titleize %></h1>
		<p class="lead"><%= Faker::Hacker.say_something_smart %></p>
		<%= simple_format(Faker::Lorem.paragraphs(3).join("\n\n")) %>
		<p class="lead"><%= number_to_currency(Faker::Number.decimal(2,2)) %></p>
		<p>
			<%= link_to '#', class: "btn btn-primary" do %>
				<span class="fa fa-shopping-cart">Dodaj do koszyka</span>
			<% end %>
		</p>
	</div>

	<div class="col-md-7">
		<%= image_tag Faker::Placeholdit.image("640x480", 'jpg', 'cccccc'), class: "img-responsive" %>
	</div>
</div>